/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:483ca5b3-6b7b-4170-b8f9-f123988beffe",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_H3poEtfZs",
    "aws_user_pools_web_client_id": "2e5iguij8k0ro14j57fs88s3b3",
    "oauth": {
        domain: 'https://expo.dev',
        scope: ['profile', 'email'],
        redirectSignIn: 'https://expo.dev',
        redirectSignOut: 'https://expo.dev',
        responseType: 'token',
        // optional, for Cognito hosted ui specified options
        options: {
          // Indicates if the data collection is enabled to support Cognito advanced security features. By default, this flag is set to true.
          AdvancedSecurityDataCollectionFlag: true
        }
    },
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "PackageRequest",
            "endpoint": "https://4mdsc8cylc.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "PackagePickup",
            "endpoint": "https://lhudgv925k.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "ParcelPalRequests-dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
