/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4b6b14d9-8633-49bb-9697-7c984dcc2379",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RSxRautOg",
    "aws_user_pools_web_client_id": "2d5g17l5vsfbc4acee5c5io6pk",
    "aws_appsync_graphqlEndpoint": 'https://7ip7t7qsgndndlqufxhr5imwve.appsync-api.us-east-1.amazonaws.com/graphql',
    "aws_appsync_region": 'us-east-1',
  "aws_appsync_authenticationType": 'API_KEY', // or other auth type
"aws_appsync_apiKey": 'da2-72jhemxmcjb53ih5z6wvaioe6e',
    "oauth": {
        domain: 'https://expo.dev',
        scope: ['profile', 'email'],
        redirectSignIn: 'https://expo.dev',
        redirectSignOut: 'https://expo.dev',
        responseType: 'token',
        // optional, for Cognito hosted ui specified options
        options: {
          // Indicates if the data collection is enabled to support Cognito advanced security features. By default, this flag is set to true.
          AdvancedSecurityDataCollectionFlag: true
        }
    },
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
